### ISSUE TITLE
[Thanks]

### ISSUE THREAD

**Issue by ITwrx** [pzmarzly/gtk-rust-test#1]
thanks for posting this. I was having trouble understanding how to *load a frikin' stylesheet* and this saved me from smashing my whole office in a hulk-like fit of rage. :)

**Comment by pzmarzly** [comment]
No problem :)

I'm not too keen on GTK, exactly because it assumes having a lot of knowledge about its (or other similar framework) architecture.

I recently got back to using GTK, as it was a part of a C programming course at my university. Rust alleviates some pain points of GTK (for example, you can `include_str` instead of [determining program install location to load Glade files](https://github.com/pzmarzly/uni-project-database-gtk/blob/75bebd87935dcc92ea12fa174faad787b5dcade4/Utils.c#L57-L71)), but makes it even harder to explore GTK features.

Speaking of that project, you may be interested in:

- [`Utils.c`](https://github.com/pzmarzly/uni-project-database-gtk/blob/75bebd87935dcc92ea12fa174faad787b5dcade4/Utils.c#L57-L126) - it showcases some GLib functions, and `remove_all_gtk_children` shows how to remove all children from GtkContainer (re-building all items on update can be considered an antipattern, but it makes the code so much simpler, and GTK is fast anyway).
- [`Datepicker.c`](https://github.com/pzmarzly/uni-project-database-gtk/blob/75bebd87935dcc92ea12fa174faad787b5dcade4/Datepicker.c) - shows how to make a dialog window
- [loading an icon at custom size](https://github.com/pzmarzly/uni-project-database-gtk/blob/75bebd87935dcc92ea12fa174faad787b5dcade4/RepoData.c#L77-L94)
